Repository future4code/mello-labenu-system3, pull requests merged in 2020-08, with the labels that each got.

#1 Commit inicial
  missions.json
  package-lock.json
  package.json
  src/FileManager.ts
  src/Student.ts
  src/Teacher.ts
  src/User.ts
  src/index.ts
  students.json
  teachers.json
  tsconfig.json
Labels: documentation

#2 Incremento classe Student.
  .gitignore
  src/Student.ts
Labels: enhancement

#3 Criação das classes Teacher e Missions; implementação das funções getAgeById e checkTeacherId
  .gitignore
  missions.json
  src/FullTimeMission.ts
  src/Mission.ts
  src/NightMission.ts
  src/Teacher.ts
  src/index.ts
  students.json
  teachers.json
Labels: enhancement

#4 Início dos desafios: Criação da classe MainTaskManager
  missions.json
  src/Data.ts
  src/MainTaskManager.ts
  src/Mission.ts
  src/Student.ts
  src/index.ts
  teachers.json
Labels: enhancement

#6 Adição da propriedade IDADE para a Classe Teachers e criação de novas instâncias de Teachers
  missions.json
  src/MainTaskManager.ts
  src/Mission.ts
  src/Teacher.ts
  src/index.ts
  teachers.json
Labels: bug

#7 Extração da funcionalidade print para um novo arquivo
  src/PrintToConsole.ts
  src/index.ts
Labels: bug

#8 Finalização do projeto LabenuSystem3 com entrega total e desafios pro…
  missions.json
  missions.txt
  package.json
  src/DataManager.ts
  src/FileManager.ts
  src/MainTaskManager.ts
  src/Mission.ts
  src/Student.ts
  src/Teacher.ts
  src/index.ts
  students.txt
  teachers.txt
Labels: Conclusão

#9 Correção de bug na lista de Teachers e refinamentos finais.
  missions.json
  src/DataManager.ts
  src/FileManager.ts
  src/MainTaskManager.ts
  src/index.ts
  teachers.json
Labels: Conclusão, bug
